### ISSUE TITLE
Limpieza de los datos

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#10]

**Comment by Joseluis0709** [comment]
En esta actividad se aplican filtros a nivel de filas en los datasets del escenario para subsanar o corregir valores fuera de rango en los siguientes atributos:

- [x] Edad
- [x] Antiguedad del empleado
- [x] Regla_pct_ingresos
- [x] hacer los de tarjetas

**Comment by aquiles98** [comment]
Realizado limpieza de datos de dataset de tarjetas y créditos. Se agrega la regla 2 y se rellena nulos de la columna tasa_interes, con promedio de la columna, luego de filtrado de los no cumplimientos de las diferentes dimensiones:
- Edad
- Antigüedad de empleado
- Regla de negocio 1
- Regla de negocio 2

**Comment by aquiles98** [comment]
Limpieza de datos documentado.
