### ISSUE TITLE
Integración de los datos

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#12]

**Comment by Joseluis0709** [comment]
A partir de los datos originales relativos al problema a resolver: 

- Datos de créditos (dataset: datos_creditos)
- Datos de productos financieros de los clientes (dataset: datos_tarjetas)

Se ha realizado una operación de unión en función de los valores del campo ‘id_cliente’, con los siguientes resultados:

**Esta parte esta en revision**
- Cantidad de columnas del dataset integrado: 23
- Cantidad de filas del dataset integrado: 10108.

**Comment by aquiles98** [comment]
A partir de los datos originales relativos al problema a resolver: 

- Datos de créditos (dataset: datos_creditos)
- Datos de productos financieros de los clientes (dataset: datos_tarjetas)
- 
Se ha realizado una operación de unión en función de los valores del campo ‘id_cliente’, con los siguientes resultados:

- Cantidad de columnas del dataset integrado: 22.
- Cantidad de filas del dataset integrado: 10103.
