### ISSUE TITLE
Generación de un plan de pruebas

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#15]

**Comment by Joseluis0709** [comment]
En primer lugar, se va a realizar una distribución de filas del dataset final integrado que ha resultado de la ejecución de las tareas de la fase de Preparación de los Datos, esta operación se realiza a fin de dar cumplimiento a las buenas prácticas planteadas en la industria y bibliografía del área:
•	Datos para entrenamiento de las técnicas: 75% - validar con Aquiles
•	Datos para prueba de los resultados obtenidos: 25% - Validar con Aquiles

**Comment by aquiles98** [comment]
Revisado modelos y plan de pruebas documentado.
