### ISSUE TITLE
Construcción del modelo

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#16]

**Comment by aquiles98** [comment]
Generación de 3 pruebas en 4 modelos diferentes, modificando los parámetros de cada uno:
- Regresión Lineal
- KNN
- Árboles de decisión
- Random Forest

Se hace la revisión en mlflow

**Comment by Joseluis0709** [comment]
Se realizaron las respectivas pruebas y estas quedaron documentadas en el entregable de la AP2
