### ISSUE TITLE
Evaluación del modelo

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#17]

**Comment by aquiles98** [comment]
Se realiza la evaluación del modelo, comparando a través de la herramienta 'mlflow', que permite hacer una revisión más rigurosa, permitiendo la facilidad de comparar diversas pruebas aplicadas a diferentes modelos.

**Comment by Joseluis0709** [comment]
Una vez comparando los resultados obtenidos, se ha seleccionado la técnica Random Forest (#3) para realizar la predicción sobre los datos correspondientes a nuevos créditos. 

Esto se ha debido a la efectividad obtenida en las diferentes instancias de evaluación que ha alcanzado el valor de 89.70% (comparado con recall de 0.97 para N y 0.58 para Y).
