### ISSUE TITLE
Evaluación de los resultados

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#18]

**Comment by aquiles98** [comment]
En función de los resultados obtenidos a partir del plan de pruebas planteado se ha seleccionado la técnica Random Forest (3) para realizar la predicción sobre los datos correspondientes a nuevos créditos. Esto se ha debido a la efectividad obtenida en las diferentes instancias de evaluación que ha alcanzado el valor de 90.06% (comparado con recall de 0.97 para N y 0.60 para Y). Pendiente por discutir con Jose.

**Comment by Joseluis0709** [comment]
Despues de revisar la tecnica a usar, con Aquiles nos dimos cuenta que el valor real es 89.70%, con los siguientes parametros:

1. bootstrap: True
2. ccp_alpha: 0.0
3. class_weight: None
4. criterion: gini
5. max_depth: None
6. max_features: sqrt
7. max_leaf_nodes: None
8. max_samples: None
9. min_impurity_decrease: 0.0
10. min_samples_leaf: 1
11. min_samples_split: 2
12. min_weight_fraction_leaf: 0.0
13. **n_estimators: 20**
14. n_jobs: None
15. oob_score: False
16. **random_state: 23**
17. verbose: 0
18. warm_start: False

**_Se resaltan los parámetros que se han modificado con respecto a su valor por defecto_**
