### ISSUE TITLE
Proceso de revisión

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#19]

**Comment by aquiles98** [comment]
En función de los datos obtenidos, la técnica seleccionada en la actividad (por definir y discutir con Jose) va a ser ejecutada sobre el dataset “datos_nuevos.csv” que se corresponde a nuevos créditos otorgados por la entidad solicitante del proyecto.
En estos datos se tendrá que predecir el valor del atributo “falta_pago” para indicar si un crédito en particular podría o no entrar en mora.
Los resultados se documentan en el apartado de “Informe Final” del presente documento.

**Comment by Joseluis0709** [comment]
Se deja constancia en los puntos anteriores y despues de la revision realizada por el equipo, se determino utilizar la prueba #3 de la técnica random forest, debido a la efectividad obtenida en las diferentes instancias de evaluación que ha alcanzado el valor de 89.70% (comparado con recall de 0.97 para N y 0.58 para Y).


Se procede con cerrar el issue
