### ISSUE TITLE
Determinación de futuras tareas

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#20]

**Comment by aquiles98** [comment]
Pendiente de revisar con Jose. Documentado 65%.

**Comment by Joseluis0709** [comment]
Se propone las siguientes columnas futuras para lograr un mejor análisis 

- Si el Cliente está radicado en el extranjero, así se podría contemplar una política monetaria del extranjero y re evaluar el posible nivel de endeudamiento.
- Cantidad de cuotas solicitadas inicialmente y otra columnas con las aprobadas
- Respaldo del préstamo (objeto, persona) - en Ecuador y Colombia, esa figura se le llama Co-deudor
- Los ingresos totales del hogar
- Las edades de las personas que tiene a cargo, si alguna de ellas tiene algún tipo de dificultad agregada que pudiera indicar una erogación en particular, entre otros.

**Comment by Joseluis0709** [comment]
Para la próxima iteración del proyecto, se propone ejecutar las siguientes tareas:

- Posibilidad de tener la base integrada desde el principio (créditos + tarjetas)
- Mejorar aspectos de calidad de datos con respecto a la presencia de valores nulos en diferentes atributos.
