### ISSUE TITLE
Plan de implantación (despliegue)

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#21]

**Comment by aquiles98** [comment]
Las autoridades de la entidad financiera han determinado que el modelo generado sea utilizado como herramienta de asesoramiento al sector de la entidad que se dedica al monitoreo de créditos. Además, se ha dispuesto realizar actualizaciones periódicas del modelo con nuevos datos que vayan siendo recolectados a lo largo del año.
Por otro lado, se ha establecido que se van a evaluar diferentes alternativas para incorporar más información socioeconómica de los clientes, aún si esto implica utilizar fuentes externas de datos.

**Comment by Joseluis0709** [comment]
Se buscaría tener acuerdos de recolección de información de data crédito como EXPERIAN para la recolección de data exógena y otros KPI´S de consideración de la rama internacional
