### ISSUE TITLE
Supervisión y mantenimiento

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#22]

**Comment by aquiles98** [comment]
Pendiente proponer acciones, junto con Jose.

**Comment by Joseluis0709** [comment]
Después de la Reunión interna que tuvimos con Aquiles, consideramos que la mejor manera de supervisión es:

1. Monitoreo de la efectividad de los resultados del producto de datos contra la realidad.
2. Documentar las diferencias para encontrar parámetros que mejoren el modelo de predicción
3. Contabilizar accesos a la herramienta por parte de los usuarios definidos para la misma.
4. Graficar predicción vs resultado, para seguimiento gerencial buscando aprobación de gerencia para reentrenamiento futuro
