### ISSUE TITLE
Redacción del informe final

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#23]

**Comment by aquiles98** [comment]
Se presentan los resultados de la aplicación del modelo generado con la técnica que ha presentado el mejor resultado en las diferentes iteraciones de pruebas aplicado sobre los datos de créditos nuevos otorgados por la entidad.



![Image](https://github.com/Joseluis0709/13MBID-Abr23/assets/134450972/5036afe8-441a-4582-8c45-4c55dde43af7)


Por revisar con Jose, en caso de modificar parámetros de modelos.

**Comment by Joseluis0709** [comment]
Al hacer la revisión en conjunto con Aquiles, nos dimos cuenta que el modelo Random Forest, compartía el mismo resultado de rendimiento obtenido, al agregarle mas criterios de evaluación, nos dimos cuenta que el resultado cambia. 

Este es el resultado final validado por los dos:



![Image](https://github.com/Joseluis0709/13MBID-Abr23/assets/143972069/b544ebea-c2cc-4bb0-be38-722e13e8981e)
