### ISSUE TITLE
Definir plan del proyecto

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#4]
Establecer las tareas del proyecto, su distribución, estimación de tamaño y esfuerzo.
Obtener los tiempos requeridos para implementar el MVP del proyecto.

**Comment by aquiles98** [comment]
Se realizó la designación de roles para el proyecto, donde ambos integrantes forman parte de las tres primeras fases de la actividad. Así mismo, se detallará más en el archivo a presentar.
