### ISSUE TITLE
Exploración de los datos

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#7]
Se requiere contar con una descripción detallada de los metadatos de cada dataset a fin de poder iniciar el proceso de exploración. Además, se podrían generar algunos gráficos de interés para visualizar detalles que pudieran ser relevantes en futuras instancias del proyecto.

**Comment by aquiles98** [comment]
Se realizó los gráficos faltantes y descripción de datos.
