### ISSUE TITLE
Verificación de la calidad de datos

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#8]
- [x] Preparar documentación
- [x] Definir criterios de análisis
- [x] Ejecutar análisis
- [x] Registrar resultados
- [ ] Proponer (en caso de corresponder) mejoras a aplicar

**Comment by aquiles98** [comment]
El desarrollo de las tareas de esta actividad se encuentra detallado en el Anexo Modelo de memoria de trabajo para evaluación de calidad de datos. Por revisar para la siguiente actividad el último punto.
