### ISSUE TITLE
Selección de datos

### ISSUE THREAD

**Issue by Joseluis0709** [Joseluis0709/13MBID-Abr23#9]

**Comment by Joseluis0709** [comment]
En función de los resultados del análisis de calidad de los datos ejecutado en la fase anterior, se realizaron los siguientes filtros a nivel de columnas en los datasets:

1. Dataset: datos_creditos – Columnas eliminadas:
     
    a. 'completitud_fila', 'situacion_vivienda_ok', 'objetivo_credito_ok', 'falta_pago_ok, para estos 4 casos, se trataron de columnas agregadas como elementos auxiliares del proceso de verificación de calidad de datos.

**Comment by Joseluis0709** [comment]
el siguiente paso es discutir con Aquiles si eliminamos LA COLUMNA TASAS DE INTERES, por que 912/10127 = 9% de esa columna tiene componentes nulos, sin embargo existe una tasa del 10% para valores nulos ... en teoria aplicaria no borrarla, pero si vamos al _atributo de valores ajustados de la dimensión exactitud_, deberíamos borrarla

**Comment by aquiles98** [comment]
Para "datos_credito_mc":

Se toma en consideración que el data set debe cumplir con las características indicadas para mantener la calidad de los datos, es decir, mantener menor al 10% los datos faltantes en las columnas. Es así que se decide rellenar los valores nulos de las columnas que no cumplen con el promedio de toda la columna. Esto se aplicará tanto para la columna "tasa_interes" y para "antiguedad_empleado", obviando los valores fuera de rango, como tener 123 años de antigüedad. 

Para "datos_tarjeta_mc":
Se toma en consideración el análisis inicial (Descripción de los datos) para identificar que en la columna "nivel_tarjeta" tiene más del 90% de los datos el valor categórico "Blue", lo que indica que es una tarjeta común. Es así que se considera que la mejor manera de seccionar es a través de el límite crediticio (limite_credito_tc)

**Comment by aquiles98** [comment]
Selección de datos culminada y documentada
